# Generated by Django 6.0.4 on 2026-04-25 15:36

import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nro_doc',
            field=models.CharField(max_length=15, unique=True, validators=[envios.validators.validar_nro_doc_dni]),
        ),
    ]
